"""Initial schema with soft delete support

Revision ID: 6311ddae9299
Revises: 
Create Date: 2025-12-01 22:53:12.268333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6311ddae9299'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comparisons', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comparisons', 'users', ['deleted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comparisons', type_='foreignkey')
    op.drop_constraint(None, 'comparisons', type_='foreignkey')
    # ### end Alembic commands ###
